import turtle
s=turtle.Turtle()
s.shape("turtle")

turtle.bgcolor("light blue")
s.hideturtle()
s.fillcolor("orange")
s.penup()
s.goto(0,50)
s.pendown()
for i in range(10):
    s.forward(100)
    s.goto(0,50)
    s.right(36)
s.penup()
s.goto(0,0)
s.pendown()
s.begin_fill()
s.circle(50)
s.end_fill()
turtle.mainloop()